default_language_version: 
  python: python3.7
repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v1.21.0
  hooks:
    - id: pyupgrade
      stages:
        - commit
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.6.1
  hooks:
  - id: reorder-python-imports
    stages:
    - commit
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
    - id: black
      args: 
        - --safe
        - --quiet
      stages:
        - commit
- repo: https://github.com/pycqa/flake8
  rev: 3.7.8
  hooks:
    - id: flake8
      stages:
        - commit
      additional_dependencies:
        - flake8-bandit
        - flake8-bugbear
        - flake8-docstrings
        - flake8-print
        - flake8-mutable
        - pep8-naming
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: 2.0.0
  hooks:
    - id: commitlint
      additional_dependencies:
        - "@commitlint/config-conventional"
      stages:
        - commit-msg
