{% set data = load_setup_py_data(setup_file="../setup.py", from_recipe_dir=True) %}

package:
  name: {{ data.get("name") }}
  version: {{ data.get("version") }}

source:
  path: ../

build:
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - ipython
    - nord-pygments
  
  test:
    - pytest
    - pytest-cov

about:
  home: {{ data["url"] }}
  license: {{ data["license"] }}
  license_file: LICENSE
  summary: {{ data["description"] }}
  dev_url: {{ data["project_urls"]["Source"] }}
