name: Continuous Integration
on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -e".[lint]"
      - name: Run linting
        run: flake8
  test:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
        os:
          - ubuntu-latest
          # - windows-latest
          # - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -e".[test]"
      - name: Run tests
        run: pytest
